config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/shared/maps/:map_id', to: 'app#shared', as: :shared_map
  get '/changelog', to: 'app#changelog'

  # Tools
  get '/tools', to: 'tools#index'
  get '/tools/soil-analysis', to: 'tools#soil_analysis'

  resources :links, except: [:show]

  namespace :api do
    api_routes_exceptions = [:new, :edit]
    no_index_api_routes_exceptions = [:index, :new, :edit]

    with_options except: api_routes_exceptions do |api_route|
      # Community-related endpoints
      api_route.resources :genera
      api_route.resources :resource_interactions
      api_route.resources :resources do
        api_route.resources :resource_interactions, only: [:index], path: 'interactions'
      end

      # Map-related endpoint, for updates and display
      api_route.resources :activities, except: no_index_api_routes_exceptions do
        get '/pictures/:picture_id', to: 'activities#picture', on: :member, as: :picture
        get '/pictures/:picture_id/thumbnail', to: 'activities#picture_thumbnail', on: :member, as: :picture_thumbnail
      end
      api_route.resources :elements, except: no_index_api_routes_exceptions do
        api_route.resources :activities, only: [:index]
      end
      api_route.resources :layers, except: no_index_api_routes_exceptions
      api_route.resources :patches, except: no_index_api_routes_exceptions do
        api_route.resources :elements, only: [:index]
      end
      api_route.resources :paths, except: no_index_api_routes_exceptions

      # Maps and their own data, for listings
      api_route.resources :maps do
        get :picture, on: :member
        api_route.resources :activities, only: [:index] do
          get '/names', to: 'activities#names', on: :collection
        end
        api_route.resources :elements, only: [:index]
        api_route.resources :layers, only: [:index]
        api_route.resources :patches, only: [:index]
        api_route.resources :paths, only: [:index]
      end
      get 'shared/maps/:id', to: 'maps#shared', as: :shared_map
    end
  end

  namespace :admin do
    resources :genera
    resources :resource_interactions
    resources :resources
    resources :links, except: [:show] do
      put :approve, on: :member
    end
  end
end

app/models/link.rb
class Link < ApplicationRecord
  validates :title, presence: true
  validates :url, presence: true
  validates :description, presence: true

  belongs_to :user
  belongs_to :approved_by, optional: true, class_name: 'User'

  has_paper_trail

  before_create :auto_approve
  after_create :notify_admins!

  scope :approved, -> { where.not(approved_by: nil) }
  scope :approved_or_owned, ->(user_id) { approved.or(where(user_id: user_id)) }

  def approved?
    !pending_approval?
  end

  def pending_approval?
    approved_by_id.nil?
  end

  private

  def auto_approve
    return unless user.admin?

    self.approved_by = user
  end

  def notify_admins!
    return if user.admin?

    User.admins.find_each do |admin|
      LinkMailer.with(recipient: admin, link: self).notify_email.deliver_later
    end
  end
end

app/controllers/admin/links_controller.rb
module Admin
  class LinksController < AdminApplicationController
    before_action :set_link, only: [:edit, :update, :approve, :destroy]

    # GET /admin/links
    def index
      @links = policy_scope Link.all
    end

    # GET /admin/links/new
    def new
      authorize Link

      @link = Link.new
    end

    # GET /admin/links/1/edit
    def edit; end

    # POST /admin/links
    def create
      authorize Link

      @link      = Link.new(link_params)
      @link.user = current_user

      if @link.save
        redirect_to admin_links_path, notice: I18n.t('admin.links.create.success')
      else
        render :new
      end
    end

    # PATCH/PUT /admin/links/1
    def update
      if @link.update(link_params)
        redirect_to admin_links_path, notice: I18n.t('admin.links.update.success')
      else
        render :edit
      end
    end

    # PATCH/PUT /admin/links/1/approve
    def approve
      @link.approved_by = current_user

      if @link.save
        redirect_to admin_links_path, notice: I18n.t('admin.links.approve.success')
      else
        redirect_to admin_links_path, alert: I18n.t('admin.links.approve.failure')
      end
    end

    # DELETE /admin/links/1
    def destroy
      @link.destroy
      redirect_to admin_links_url, notice: I18n.t('admin.links.destroy.success')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])

      authorize @link
    end

    # Only allow a trusted parameter "white list" through.
    def link_params
      params.require(:link).permit(:title, :url, :description)
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:edit, :update, :destroy]

  # GET /links
  def index
    @links = policy_scope Link.order(title: :asc)
  end

  # GET /links/new
  def new
    authorize Link

    @link = Link.new
  end

  # GET /admin/links/1/edit
  def edit; end

  # POST /links
  def create
    authorize Link

    @link = Link.new(link_params)
    @link.user = current_user

    if @link.save
      redirect_to links_path, notice: I18n.t('links.create.success')
    else
      render :new
    end
  end

  # PUT /links/1
  def update
    if @link.update(link_params)
      redirect_to links_path, notice: I18n.t('links.update.success')
    else
      render :edit
    end
  end

  # DELETE /links/1
  def destroy
    @link.destroy
    redirect_to links_path, notice: I18n.t('links.destroy.success')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])

    authorize @link
  end

  def link_params
    params.require(:link).permit(:title, :url, :description)
  end
end

app/views/admin/links/_form.html.haml
- url = link.id ? admin_link_path : admin_links_path
= form_for link, url: url, html: { class: 'form' } do |f|
  - if link.errors.any?
    .alert.alert--alert
      %p= t('.errors', count: link.errors.count)
      %ul
        - link.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title, required: true
  .field
    = f.label :url
    = f.text_field :url, required: true
  .field
    = f.label :description
    = f.text_field :description, max: 255, required: true

  .form__actions
    = f.submit t('generic.save'), class: 'recorder'

app/views/admin/links/edit.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), :admin_links, role: 'button'
  = link_to t('generic.show'), @admin_link, role: 'button'
  = link_to t('generic.destroy'),
            @admin_link,
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button'

= render 'form', link: @link

app/views/admin/links/index.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('.new'), new_admin_link_path, role: 'button', class: 'creative'

- if @links.count.zero?
  .alert.alert--empty= t('.no_content')
- else
  %table
    %caption.sr-only= t('.table_caption')
    %thead
      %tr
        %th{ scope: 'col' }= t('activerecord.attributes.link.title')
        %th{ scope: 'col' }= t('activerecord.attributes.link.url')
        %th{ scope: 'col' }= t('activerecord.attributes.link.description')
        %th{ scope: 'col' }= t('activerecord.attributes.link.approved_by')
        %th{ scope: 'col' }

    %tbody
      - @links.each do |link|
        %tr.link{ class: link.pending_approval? ? 'link--pending' : '' }
          %td= link_to link.title, admin_link_path(link)
          %td= link.url
          %td= link.description
          %td
            - if link.approved?
              = link.approved_by.username
            - else
              = link_to t('.approve'), approve_admin_link_path(link), class: 'button', method: :put
          %td.actions
            = link_to t('generic.edit'), edit_admin_link_path(link), role: 'button'
            = link_to t('generic.destroy'),
                      admin_link_path(link),
                      method: :delete,
                      data: { confirm: t('generic.are_you_sure') },
                      role: 'button',
                      class: 'destructive'

app/views/admin/links/new.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), admin_links_path, role: 'button'

= render 'form', link: @link