config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'app#home'

  get '/app', to: 'app#app'
  get '/shared/maps/:map_id', to: 'app#shared', as: :shared_map
  get '/changelog', to: 'app#changelog'

  # Tools
  get '/tools', to: 'tools#index'
  get '/tools/soil-analysis', to: 'tools#soil_analysis'

  resources :links, except: [:show]

  namespace :api do
    api_routes_exceptions = [:new, :edit]
    no_index_api_routes_exceptions = [:index, :new, :edit]

    with_options except: api_routes_exceptions do |api_route|
      # Community-related endpoints
      api_route.resources :genera
      api_route.resources :resource_interactions
      api_route.resources :resources do
        api_route.resources :resource_interactions, only: [:index], path: 'interactions'
      end

      # Map-related endpoint, for updates and display
      api_route.resources :activities, except: no_index_api_routes_exceptions do
        get '/pictures/:picture_id', to: 'activities#picture', on: :member, as: :picture
        get '/pictures/:picture_id/thumbnail', to: 'activities#picture_thumbnail', on: :member, as: :picture_thumbnail
      end
      api_route.resources :elements, except: no_index_api_routes_exceptions do
        api_route.resources :activities, only: [:index]
      end
      api_route.resources :layers, except: no_index_api_routes_exceptions
      api_route.resources :patches, except: no_index_api_routes_exceptions do
        api_route.resources :elements, only: [:index]
      end
      api_route.resources :paths, except: no_index_api_routes_exceptions

      # Maps and their own data, for listings
      api_route.resources :maps do
        get :picture, on: :member
        api_route.resources :activities, only: [:index] do
          get '/names', to: 'activities#names', on: :collection
        end
        api_route.resources :elements, only: [:index]
        api_route.resources :layers, only: [:index]
        api_route.resources :patches, only: [:index]
        api_route.resources :paths, only: [:index]
      end
      get 'shared/maps/:id', to: 'maps#shared', as: :shared_map
    end
  end

  namespace :admin do
    resources :genera
    resources :resource_interactions
    resources :resources
    resources :links, except: [:show] do
      put :approve, on: :member
    end
  end
end

app/views/admin/resources/_form.html.haml
- url = resource.id ? admin_resource_path : admin_resources_path
= form_for resource, url: url, html: { class: 'form' } do |f|
  - if resource.errors.any?
    .alert.alert--alert
      %p= t('.errors', count: resource.errors.count)
      %ul
        - resource.errors.full_messages.each do |message|
          %li= message

  .page--show
    %section.page__panel
      .field
        = f.label :name
        = f.text_field :name, required: true
      .field
        = f.label :color do
          = t('activerecord.attributes.resource.color')
          .color_preview#color-preview
        = f.text_field :color, required: true
      .field
        = f.label :common_names
        = f.text_field :common_names, value: resource.common_names.join(', ')
        .field__help= t('generic.comma_separated_values')
      .field
        = f.label :source
        = f.text_field :source
      .field
        = f.label :edible do
          = f.check_box :edible
          = t('activerecord.attributes.resource.edible')
      .field
        = f.label :parent_id, t('activerecord.attributes.resource.parent')
        = f.collection_select :parent_id, Resource.all.order(:name), :id, :name, prompt: true
      .field
        = f.label :genus_id, t('activerecord.attributes.resource.genus')
        = f.collection_select :genus_id, Genus.all.order(:name), :id, :name, required: true
    %section.page__content
      .field
        = f.label :description
        = f.text_area :description, required: true, class: 'textarea-markdown textarea--large'

  .form__actions
    = f.submit t('generic.save'), class: 'recorder'

:javascript
  function updateColorPreview() {
    var target = document.getElementById('color-preview')
    var input  = document.getElementById('resource_color')
    var valid = true
    input.value.split(',').map(function(c) {return c.trim()}).forEach(function(e) {
      var value = parseInt(e, 10)
      if(!/^\d{1,3}$/.test(e) || value > 255 || value < 0) valid = false
    })
    if(valid) {
      target.style.backgroundColor= 'rgb('+input.value+')'
      input.setCustomValidity('');
    } else {
      input.setCustomValidity('#{escape_javascript(t('activerecord.errors.bad_color_segment'))}');
    }
  }
  document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('resource_color').addEventListener('input', updateColorPreview)
    updateColorPreview()
  })

app/views/admin/resources/edit.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), :admin_resources, role: 'button'
  = link_to t('generic.show'), @admin_resource, role: 'button'
  = link_to t('generic.destroy'),
            @admin_resource,
            method: :delete,
            data: { confirm: t('generic.are_you_sure') },
            role: 'button'

= render 'form', resource: @resource

app/views/admin/resources/index.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('.new'), new_admin_resource_path, role: 'button', class: 'creative'

- if @resources.count.zero?
  .alert.alert--empty= t('.no_content')
- else
  %table
    %caption.sr-only= t('.table_caption')
    %thead
      %tr
        %th{ scope: 'col' }= t('activerecord.attributes.resource.name')
        %th{ scope: 'col' }= t('activerecord.attributes.resource.edible')
        %th{ scope: 'col' }= t('activerecord.attributes.resource.parent')
        %th{ scope: 'col' }= t('activerecord.attributes.resource.layer')
        %th{ scope: 'col' }= t('activerecord.attributes.resource.genus')
        %th{ scope: 'col' }

    %tbody
      - @resources.each do |resource|
        %tr
          %td= link_to resource.name, admin_resource_path(resource)
          %td= yes_no resource.edible
          %td= resource.parent.presence&.name || '-'
          %td= resource.genus.name
          %td.actions
            = link_to t('generic.edit'), edit_admin_resource_path(resource), role: 'button'
            = link_to t('generic.destroy'),
                      admin_resource_path(resource),
                      method: :delete,
                      data: { confirm: t('generic.are_you_sure') },
                      role: 'button',
                      class: 'destructive'

app/views/admin/resources/new.html.haml
- @page_title = t('.title')

.page__actions
  = link_to t('generic.back'), admin_resources_path, role: 'button'

= render 'form', resource: @resource

app/views/admin/resources/show.html.haml
- @page_title = t('.title', name: @resource.name)

.page__actions
  = link_to t('generic.back'), admin_resources_path, role: 'button'

  - if policy([:admin, @resource]).edit?
    = link_to t('generic.edit'), edit_admin_resource_path(@resource), role: 'button'
  - if policy([:admin, @resource]).destroy?
    = link_to t('generic.destroy'),
              admin_resource_path,
              method: :delete,
              data: { confirm: t('generic.are_you_sure') },
              role: 'button',
              class: 'destructive'
.page--show
  %aside.page__panel
    %section
      %dl
        %dt= t('generic.definition', value: t('activerecord.attributes.resource.genus'))
        %dd= link_to @resource.genus.name, admin_genus_path(@resource.genus)

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.source'))
        %dd= @resource.source

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.common_names'))
        %dd
          - if @resource.common_names.size.zero?
            \-
          - else
            %ul
              - @resource.common_names.each do |cn|
                %li= cn

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.edible'))
        %dd= yes_no @resource.edible

        %dt= t('generic.definition', value: t('activerecord.attributes.resource.parent'))
        %dd= @resource.parent ? @resource.parent.name : '-'

  .page__content
    %h2= t('activerecord.attributes.resource.description')
    #markdown
      #markdown-source= @resource.description

    - if @resource.parent.blank?
      %h2= t('.resources')
      - if @resource.children.size.zero?
        .alert.alert--mute= t('.no_child_resource')
      - else
        %ul
          - @resource.children.each do |resource|
            %li= link_to resource.name, admin_resource_path(resource)

:javascript
  renderMD(document.getElementById('markdown'), document.getElementById('markdown-source'))